### ISSUE TITLE
Is this library planned to be compatible with .NET 8?

### ISSUE THREAD

**Issue by phasetr** [ganhammar/AspNetCore.Identity.AmazonDynamoDB#2]
Now I plan to use this library with .NET8. Is this library planned to be compatible with .NET8?
Furthermore do you have some (small) sample project?

**Comment by ganhammar** [comment]
Just released version 1.1.0 which adds net8.0 as target framework, so, yes, it should support .NET8.

I don't have a small sample project, I do however have a [hobby project](https://github.com/ganhammar/what-did-i-do-login/tree/main) which you could refer to. I'll consider adding a sample project! 👍

**Comment by phasetr** [comment]
Thank you for your version up and comments! I'll also check your project.
