### ISSUE TITLE
Adding a new external login provider to an existing user replaces the old one

### ISSUE THREAD

**Issue by abc-rpg** [ganhammar/AspNetCore.Identity.AmazonDynamoDB#49]
### Summary

When trying to add a new external login provider to an existing user (calling `UserManager.AddLoginAsync(user, loginInfo)`, it will remove the previous login provider from the DynamoDb table.

### Desired Outcome

Adding a new login provider to an existing user with a different login provider should add it alongside it (so the user is able to use either of the two login providers).

### Why it happens

* In the [UserManager.AddLoginAsync](https://github.com/aspnet/AspNetIdentity/blob/main/src/Microsoft.AspNet.Identity.Core/UserManager.cs#L791) method we fetch the existing user first. In the case of the DynamoDb store, the logins are not included.
* The call to [DynamoDbUserStore.AddLoginAsync()](https://github.com/ganhammar/AspNetCore.Identity.AmazonDynamoDB/blob/main/src/AspNetCore.Identity.AmazonDynamoDB/Stores/DynamoDbUserStore.cs#L94) will initialize the `user.Logins` collection and add the new login provider.
* Finally it calls the [DynamoDbUserStore.UpdateAsync()](https://github.com/ganhammar/AspNetCore.Identity.AmazonDynamoDB/blob/main/src/AspNetCore.Identity.AmazonDynamoDB/Stores/DynamoDbUserStore.cs#L702) with that `user` object, which will cause any logins in DynamoDb that are not in the user object to be deleted.

### Solution/Workaround

I updated [DynamoDbUserStore.AddLoginAsync](https://github.com/ganhammar/AspNetCore.Identity.AmazonDynamoDB/blob/main/src/AspNetCore.Identity.AmazonDynamoDB/Stores/DynamoDbUserStore.cs#L89) to call `GetRawLogins` instead of initializing the collection. It looks like this:

```csharp
  public async Task AddLoginAsync(TUserEntity user, UserLoginInfo login, CancellationToken cancellationToken)
  {
    ArgumentNullException.ThrowIfNull(user);
    ArgumentNullException.ThrowIfNull(login);

    user.Logins = await GetRawLogins(user, cancellationToken); // this was updated

    user.Logins.Add(new DynamoDbUserLogin
    {
      LoginProvider = login.LoginProvider,
      ProviderKey = login.ProviderKey,
      ProviderDisplayName = login.ProviderDisplayName,
      UserId = user.Id,
    });
  }
```

This adds the new login provider while keeping the old one. I can then also successfully remove one of those providers successfully. I'm just not confident this is the right way to fix it.

### Test

This test replicates the issue, and passes with the above change.

```csharp
  [Fact]
  public async Task Should_AddSecondLogin_When_LoginProviderIsNew()
  {
    // Arrange
    var context = new DynamoDBContext(DatabaseFixture.Client);
    var options = TestUtils.GetOptions(new() { Database = DatabaseFixture.Client });
    var userStore = new DynamoDbUserStore<DynamoDbUser>(options);
    await AspNetCoreIdentityDynamoDbSetup.EnsureInitializedAsync(options);
    var user = new DynamoDbUser();

    var login = new DynamoDbUserLogin
    {
      LoginProvider = "first",
      ProviderKey = Guid.NewGuid().ToString(),
      UserId = user.Id,
    };
    await context.SaveAsync(login);

    // Act
    await userStore.AddLoginAsync(
      user, new("second", "second", "second"), CancellationToken.None);

    // Assert
    Assert.Equal(2, user.Logins!.Count);
  }
```

**Comment by ganhammar** [comment]
Hey!

Thanks for creating the issue and taking the time to describe it in such detail and providing a solution! Your suggested solution seems reasonable to me, I would gladly accept a pull request if you have the time to create one. Otherwise, I'll look into it this week :)

**Comment by abc-rpg** [comment]
No problem. I could not push a branch to this repository so I had to make a fork to create the PR. But that does not seem to trigger the ci/cd action which is expected for the PR 🤔

**Comment by ganhammar** [comment]
@abc-rpg 1.2.1 should sone be available on NuGet with your fix!
